version: '3.7'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8300
    volumes:
      - ./app/:/dev_app
    container_name: portfolio_dev
    ports:
      - 8300:8300
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    container_name: portfolio_db_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=rozaq
      - POSTGRES_PASSWORD=rozaq
      - POSTGRES_DB=portfoliodb
    ports: 
      - '8320:5432'

volumes:
  postgres_data: